version: '2.1'
services:
    solo:
        build:
            context: .
            dockerfile: Dockerfile
        image: playingjoker/solo:latest
        ports:
            - "8800:8800"
        volumes:
            - "${HOME}/.solo_data/logs:/data/logs"
        restart: always
